/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.programmer3481.simple3d;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Simple3D classUnderTest = new Simple3D();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
}
